### ISSUE TITLE
TOBOOT_CONFIG_FLAG_AUTORUN

### ISSUE THREAD

**Issue by Honos2014** [im-tomu/tomu-quickstart#28]
I'm deffinitively missing something...
How should I enable/disable TOBOOT_CONFIG_FLAG_AUTORUN ??

Tomu always returns to programming mode.
How can I make my program runs when inserting Tomu?
 
Thanks

**Comment by xobs** [comment]
Add it to the `TOBOOT_CONFIGURATION()` declaration:

```c++
// Make this program compatible with Toboot-V2.0
#include <toboot.h>
TOBOOT_CONFIGURATION(TOBOOT_CONFIG_FLAG_AUTORUN);
```

**Comment by Honos2014** [comment]
I did try that without good result. But I'll try again soon.
I'll let you know.
Thank you.

**Comment by mithro** [comment]
Please make sure your running that latest bootloader.

**Comment by Honos2014** [comment]
Thank you both.
I flashed latest tomu-bootloader and added
// Make this program compatible with Toboot-V2.0
#include <toboot.h>
TOBOOT_CONFIGURATION(TOBOOT_CONFIG_FLAG_AUTORUN);

Perfect!
