### ISSUE TITLE
arm-none-eabi/bin/ld: cannot find -lstdc++ error when running make 

### ISSUE THREAD

**Issue by gbrayut** [im-tomu/tomu-quickstart#9]
On Linux Mint 18.3 (based on Ubuntu 16.04) I kept getting the following error trying to run make:

```
$ make
  CC       miniblink.c	miniblink.o
  LD       miniblink.elf
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
../Makefile.common:59: recipe for target 'miniblink.elf' failed
make: *** [miniblink.elf] Error 1
```
I had installed the listed tools using `sudo apt-get install gcc-arm-none-eabi libnewlib-arm-none-eabi make dfu-util` but it seems there is one more that is required (at least for my system). After installing the  `libstdc++-arm-none-eabi-newlib` package I was able to build the example files.

Didn't see much detail about this error online, so figured I would add a note here. May want to update the docs.

Thanks!

**Comment by xobs** [comment]
Thanks!  I've added that package to the setup docs as part of commit e4d6d9e442f4c344533025bc946379950ea281be
