### ISSUE TITLE
Question for HID keyboard example

### ISSUE THREAD

**Issue by kastriotfetahaj** [im-tomu/tomu-quickstart#96]
Hi, I am using the following example: https://github.com/im-tomu/tomu-quickstart/tree/master/usb-hid-keyboard

But I can not find a way how to send GUI +r keys at the same time and I can not find a way to send ENTER as e key,

Can anyone help me on that?

**Comment by evyatartamir** [comment]
@kastriotfetahaj You can send a Modifier Key, for example the Left Gui key, and "r" in the same report. See [here](https://wiki.osdev.org/USB_Human_Interface_Devices#Report_format) for the report format.

To inject the "Enter" key, I modified the injkeys() function to convert ASCII CR ('\r' == 0xD) to its USB [HID scancode](https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf) (40 decimal):

```
else if(source[j]=='\r') // CR (Enter)
	buf[2]=40;
```

I wrote and tested a function to open "notepad" on Windows, you can call it before the calls to injkeys() in the sys_tick_handler.

```
// Open "notepad" in Windows
void run_notepad()
{
	#define LEFT_GUI_KEY 0x08 // Key modifier
	
	// Inject Left Gui (Winkey) + "r", to open the "run" console
	injkeys("r", LEFT_GUI_KEY);

	//Wait for the "run" console to open before injecting command
	for (unsigned int i = 0; i != 1500000; ++i) {
		__asm__("nop");
	}

	// Inject string "notepad" + Enter key
	injkeys("notepad\r",0);
}
```

**Comment by evyatartamir** [comment]
@xobs Following PR #115, can this issue be closed?

**Comment by xobs** [comment]
Yes, that does seem to solve this issue.
